name: 02-Workflow-Events

on:
  # push:
  # pull_request:
    workflow_dispatch:
  # schedule:
   #     - cron: "*/5 * * * *" # every 5 minutes

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "This workflow runs on ${{ github.event_name }} event!"
