name: 03-Workflow-Runners

on: 
    push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run:  |   
                    echo "This job running on an Ubuntu runner!
                    echo "{{ runner.os }}"

    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: | 
                    echo "This job running on a Windows runner!"
                    echo "{{ runner.os }}"

    macos-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run:  |
                    echo "This job running on a macOS runner!"
                    echo "{{ runner.os }}"

                    